### ISSUE TITLE
Theme fails to build styles

### ISSUE THREAD

**Issue by slimeygecko** [connor-baer/autumn#18]
I've tried to clone and build this theme with no luck. Any ideas?

```
Details:
    status: 1
    file: node_modules/mappy-breakpoints/_mappy-breakpoints.scss
    line: 42
    column: 5
    formatted: Error:  does not contain tablet
        on line 42 of node_modules/mappy-breakpoints/_mappy-breakpoints.scss, in mixin `mappy-query`
        from line 35 of _scss/core/_metabar.scss
        from line 45 of _scss/styles.scss
>>     @error "#{$mappy-queries} does not contain #{$query}";
```

**Comment by connor-baer** [comment]
No clue. The `tablet` value is defined in the [`core/_layout.scss`](https://github.com/connor-baer/autumn/blob/master/_scss/core/_layout.scss#L22) file which is imported before the `core/_metabar.scss` file, so it should be available. 

Have you made any changes to the code?

**Comment by slimeygecko** [comment]
No that's happening on a fresh clone of the repo. Do you have recommended versions of node and ruby to run this on? I had issues getting this far with ruby. I solved that by deleting the `Gemfile.lock` file and running the `bundle install` command.

**Comment by connor-baer** [comment]
@slimeygecko I've not used this theme in over 2 years so I don't remember what version I used. I suspect they would be out of date by now anyway. As the readme states:

> ⚠️ This theme should work as-is, but is no longer actively maintained. [Contributions](https://github.com/connor-baer/autumn#contributing) are welcome!

Sorry I can't help more!

**Comment by slimeygecko** [comment]
That's ok, if I get it working, I'll open a pull request.
